### ISSUE TITLE
uuid for Profile struct

### ISSUE THREAD

**Issue by dauphin3** [holochain-open-dev/profiles#56]
It would be convenient to have a uuid field outside the BTreeMap to link to various things, like AgentPubKey

This would allow for changing the nickname, although I'm not sure if that is desired (but Im thinking there may be advantages for a static object linked instead of nickname) then that static object could be linked to the nickname/handle

perhaps it makes sense to make the uid the AgentPubkey

thoughts on the tradeoffs between have both, or just a uuid to linked to an Agent, or none of the above?

**Comment by guillemcordoba** [comment]
Mmm I'm not sure I follow. It is already possible to change the nickname, using the `update_profile` zome function.

What would be the objective of adding a uuid? To disambiguate between profile entries? I'm not sure what that would accomplish since we are only referencing actions that create profile entries, so those action hashes are always unique already.

**Comment by dauphin3** [comment]
this issue is what made me think of it
https://github.com/GeekGene/MewsFeed/issues/88

also some potential advantages:
-tracking profile updates
-identifying spammers
-opening ways to link additionally metadata

**Comment by dauphin3** [comment]
I can start a discussion topic on the forum, see above link for chat about
migration

**Comment by guillemcordoba** [comment]
I'm going to close this for now as "not needed", because the `ActionHash` will always be unique for an agent creating a profile.
